### ISSUE TITLE
Latest hxcpp causes fatal error C1041 on MSVC2013

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#152]
Latest version of hxcpp causes C1041: Cannot open program database error on several places.

OpenALBindings.cpp :
ExternalInterface.cpp
OGG.cpp
JPEG.cpp
Font.cpp

Source Files including build.xml
https://www.dropbox.com/s/k0x8t0sfru9635u/lime_hxcpp_build.zip?dl=0

Looks like this issue occurs from this commit.
Setup MSVC before including build.xml · db9ee5f · HaxeFoundation/hxcpp https://github.com/HaxeFoundation/hxcpp/commit/db9ee5f3ee69f3d38ae86280bd5c300e6b1186aa

**Comment by hughsando** [comment]
There seems to be some log missing after "C:/HaxeToolkit/haxe/lib/hxcpp/git/toolchain/finish-setup.xml".
The end of this file should call ``` <setup name="msvc"/>```, which should log something like ```Using msvc cl version 18```.  The environment variables NO_AUTO_MSVC and HXCPP_MSVC_CUSTOM could prevent this - do you have these set?  Otherwise, if you could use "trace" and rebuild from tools/hxcpp to ensure that Setup.setupMSVC is being called, we should be able to get to the bottom of the problem.

**Comment by vroad** [comment]
Sorry I just forgot to rebuild tools before compiling.
The name of obj directory now became "mscv18-debugxp".
