### ISSUE TITLE
Using val_is_buffer against non-buffer values makes neko crash

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#154]
While I was trying to fix the problem of receiving ImageBuffer from node.js, I found that val_is_buffer doesn't work for non-buffer values.
Probably neko does not check if value is really buffer or not. Is this a problem of CFFILoader, or neko?

I could workaround this by moving val_is_buffer to another place.

https://github.com/vroad/lime/commit/090c9f1227b40fd51da460cea453d46af0097a06
https://github.com/vroad/lime/commit/4bd82205f126c9757b37a3b9e113daf27d5854a6

**Comment by hughsando** [comment]
Actually, it looks like val_is_buffer is not going to work on neko.  In fact the 'buffer' code looks a bit messed up because hxcpp uses a "byte array" for 'buffer', but neko does something quite different so you can't really treat it as a slab of bytes without getting some kind of string-copy.
I have fixed this now by having val_is_buffer always return false on neko, since you can't store the buffer back into a neko value without a copy.  So you will probably need to see if the value you are interested in is a string - which is the neko version of a byte-slab - if val_is_buffer fails.
