### ISSUE TITLE
Support for hiding window on process_run in Process.cpp 

### ISSUE THREAD

**Issue by nescribal** [HaxeFoundation/hxcpp#169]
I'm running a program on Windows and I wanted to hide console window. I noticed looking on Process.cpp code that this could be done on line 132 of Process.cpp:

```
sinf.wShowWindow = hideWindow ? SW_HIDE : SW_NORM;

```
and adding a third int parameter to process_run hideWindow with 0 default so api remains as it is. Or maybe overloading method process_run.

Could this be done? Would you prefer me to do a pull request?

Thanks!

**Comment by hughsando** [comment]
This is a bit of a tricky on since the sys.io.Process class is part of the core Api (eg, supported by neko too) so changing the API would involve some discussion.  Also, this parameter  only really makes sense on windows.  So having a new function, say, "process_run_windows" and moving most of the process_run code into a process_run_common function could solve the problem.  The extra parameter may as well be the the windows integer constant (eg, maybe start minimized) in this case.
Not sure where where to put the .hx code that goes with this, because of the core api issue.

**Comment by hughsando** [comment]
I have added the function to cpp.NativeProcess to allow then creation of a process with a given show parameter.  You will still need to duplicate the logic in sys.io.Process.hx somehow, although all the functions are available in NativeProcess.
