### ISSUE TITLE
3.2.0-rc.1; Options.txt format change notes

### ISSUE THREAD

**Issue by underscorediscovery** [HaxeFoundation/hxcpp#187]
From what I can tell, the changes are:

`before`
two lines only, with quotes, with -D. line1=flags, line2=hxcpp path
```
-Darch_64="1" -Dblah="blah"
hxcpp/path/
```
after: multiple lines, no quotes, no -D, all flags
```
arch-64=1
arch_64=1
blah=blah
hxcpp=hxcpp/path/
```

So is the expected usage is now `.split('\r?\n').join(' -D')` or similar? 
Can we document this change in the notes as it affects build tools that use `-no-compilation`.
Also: If anything else changed regarding the Options.txt (like if it is being internally loaded and we don't need to pass these anymore?) that would be good.

I think the one line per flag is better, btw.

**Comment by underscorediscovery** [comment]
I'd also be curious as to the effect of no quotes this might have - say if your haxelib folder has a space in the path, it might be required to wrap the args (on the user side I think) in quotes anyway

**Comment by hughsando** [comment]
All I actually use the Options.txt file for is dependency checking - if a
define is added that affects the compile, I can mark all the files as
out-of-date.  In this case, it does not really matter about the format of
the file, since it is just checked byte-for-byte.
I changed this to filter out defines that do not effect the compiler args
(eg any define that changes the generated code, but not the compiler flags
can be ignored) so you do not have to recompile everything if you don't
have to.
I has not really thought about the no-compile case.  Maybe if I just read
the defines from Options.txt as if they came from the command-line, that
would solve everyone problem.
Alternatively, If you are generating the haxe command yourself, I think you
can generate the "haxelib run hxcpp" commands with the same defines and
ignore the Options.txt, since I think the only "magic" flag is the
hxcpp_api_level, but this should also be in the Build.xml
For reading, I think the logic would be to first split on the new line,
then the '=' sign, ignore 'hxcpp', then reconstitute by quoting the parts
after the '=' sign.

**Comment by underscorediscovery** [comment]
Well, the reason I have to use Options.txt is because of the `hxcpp_api_level`. For lib builds (haxelib run hxcpp manual) there is no Options.txt anyway (and api level doesn't matter there).

So at the time, I had this problem of the code compiling with hxcpp_api_level not being defined by the build tool because I was ignoring Options.txt (and I wasn't passing the user defines to hxcpp either). 

To fix this - I used options.txt (and I think lime/openfl does too). I had to get this non-user information from somewhere - and I checked around and found it seemed to be the Options.txt. This fits my needs - it's brutally simple to parse, and doesn't incur a huge xml parser dependency to read a single int value.

Maybe I can just scoop the hxcpp_api_level from this file using regex? But if it's going to randomly change in format this will continue to break each revision. Currently I have to handle both 3.1.3 output and 3.2.0 output which is not too bad, but I worry that future changes will make this worse and miss on critical flag introductions during dev or releases. I want to avoid this being brittle as it impacts the builds working at all (and is hard to debug what the reasons are for the errors being a missing internal flag).

Maybe all "non-user" flags should be written in a separate file in a fixed way, and future flags would automatically be caught by this? Something like `hxcppflags.txt` that just contains these special compiler defines that aren't possible to deduce from the code or user.

Or, we can make Options.txt consistent using the one entry per line with quotes from here on forward and keep it simple. This would suit existing tools because they only have to account for the minor changes in 3.1 > 3.2 and nothing else, and can continue to use the Options for build flags to hxcpp.  

Maybe there's a better way to get these special defines for now and future that is more bulletproof?

**Comment by hughsando** [comment]
The options that affect the compiler switches all contain "hxcpp" (case
insensitive)  or "dll" (legacy naming).  However, more information can get
passed - eg a library may inject some xml that then relies on a define from
the developer.

I think the real issue here is that I have considered "Options.txt"
internal "undocumented" and therefore changeable as I see fit.  If the
functionality is needed then there are 2 options as I see:
1. Document it and "lock it in"
2. Find the needed functionality elsewhere and keep Options.txt internal

Both are reasonable options - it depends on how people are using this
information.  eg, If hxcpp read the defines from Options.txt, would that
solve the problem?
Another option might be "-options-file my_options.txt" to allow arbitrary
options (name=value) pairs to be read from a file - could be useful
elsewhere, or with modified options.  This would also involve locking-in
the file format.

Out of interest, what is missing that makes  no-compilation necessary?

**Comment by hughsando** [comment]
So, moving forwards, either projects that use Options.txt are going to need to change, or gencpp.ml is going to need to change.  gencpp.ml can change before 3.2 release I think, but if the projects need special 3.2 releases (eg, for native properties) anyhow, I would prefer we all move to a new system that solves all the issues.

**Comment by underscorediscovery** [comment]
I think the new file as it stands is already better, but I think it has the problems with the formatting.

What I think would be good:
 - one flag per line
 - manual `-D` is inconsequential, but better to add imo (see below)
 - manual `" "` is finicky and error prone. i'd rather it solve at the source.

Current (3.2.0 rc.1):
```
flag0=val0
flag1=val1
flag2=val2
```

Better:
```
flag0="val0"
flag1="val1"
flag2="val2"
```

Even Better:
```
-Dflag0="val0"
-Dflag1="val1"
-Dflag2="val2"
```

Why do I prefer this? 
 - One source, One place to fix problems. One place to update. One place to maintain in future and align with.
 - File is already there. File is already used exactly for this purpose by openfl + flow.
 - Pass through is super easy. From CLI piping to build tools, it's easy to use (easier on one line for piping, but not really a back breaker)
 - Hard to get wrong.

If that was locked down I think it would be good for every current use.

With regards to other options:
- hxcpp consumes the Options.txt automatically
   - This is a good option I think as well.
   - This removes the need for the build tools to do parsing/consuming 
   - Allows you to change it since you are creating and consuming it, if that need arises. But a locked in format would be good either way - especially one that allows tying build systems in that aren't reliant on complex code i.e bat and bash on a build server.

With regards to no-compilation:
- I sometimes need to do things in between haxe and hxcpp compile. 
- I sometimes want haxe compile without hxcpp
- I sometimes want hxcpp without haxe (libs too)
- I inject custom build.xml in front of haxe generated one.

I can't use haxe -> hxcpp, it just doesn't work for my needs.

**Comment by hughsando** [comment]
I do not really like the -D and quotes per line, since it introduces things
such as quoting-a-quote, and will make parsing data out and processing
harder for libraries.
If we agree that the library code need to change, I would much prefer the
library does:
haxelib run hxcpp -options Options.txt
rather than:
haxelib run hxcpp `cat Options.txt`
Which is what I think things are going to amount to.
Infact, reversing it to use Options.txt by default may be better: haxelib
run hxcpp -no-options, or maybe haxelib run hxcpp -options "" to allow
replacement.
This would make the use case of tinkering with the generated code just work
be default.  As for your use-cases, I appreciate the need for the
no-compilation (in general), I was more wondering about the specifics of
how these would interact with "read the options.txt by default" solution.

So my current thinking is:
1. Add a "-options" flag to hxcpp, which allows specifying a different (or
no) Options.txt file, but otherwise read Options.txt by default.
2. Lock in the current format
3. Ignore (but with warning) abc=def on the command line, since I think
openfl may generate 1 (but not all) of these from the current options.txt

This will allow an updated hxcpp to compile existing projects with 3.2 rc1
until libraries can be changed.
I think the library code will then be easier to maintain, because if it
does not need to mess with the options, it does not need to do anything.
If it does, then re-writing the options.txt will not require a complex
regex or anything to parse and re-constitute.

**Comment by underscorediscovery** [comment]
Ok, to recap: my only “problem” was the use case of dealing with haxe generated defines that hxcpp needs. 

Your solution solves this, reduces code complexity and chance of error in libraries, reduces `if 3.2` like code, and prevents breakage on future updates. To solve it only requires a newer hxcpp, plus the libraries remove their manual parsing (unless really needed) of Options.txt. 

This sounds like a great option to me. "Just works", allows modifying because the format is fixed and can be updated before hxcpp call if necessary. I think the simplicity of the format then is ok.

> 3. Ignore (but with warning) abc=def on the command line, since I think
openfl may generate 1 (but not all) of these from the current options.txt

I think that it might be all - but it rejects on the first one. I removed the first line to test as it had a `-` in it, and it rejected on the next line but maybe it was coincidence. 

Either way: I think that ignore + warning would be best especially because "is not a target" is an unrelated error to the input (defines), so it's hard for users that don't understand this system to find a cause.

Still I think @jgranick might have an opinion - but I'd be happy to move forward this way.

**Comment by hughsando** [comment]
Good.  I am actually thinking about allowing abc=def - with the Options.txt
automatically read there should be no issues of missing defines, and this
syntax is the same as "make" so is probably nicer anyhow.
Joshua apparently has the openfl release under control, so any issues wont
last long.
I'm looking to do a mini hxcpp release in a day or two, so I will roll this
in - and keep the Options.txt format as is now from now on.

**Comment by Simn** [comment]
Is this going to require a Haxe update?

**Comment by hughsando** [comment]
No - think I can do it from a hxcpp update.

**Comment by underscorediscovery** [comment]
Sounds good. I'll leave this open and you can close it with the commits for that, I'll test it when it's in. :+1:

**Comment by hughsando** [comment]
See if the git version or
http://nmehost.com/releases/hxcpp/hxcpp-3.2.29.zip
does the job for you.

**Comment by underscorediscovery** [comment]
When trying to build a prebuilt dll:

`haxelib run hxcpp library.xml`
`Error: Could not find dependencies: [ Options.txt ]`

**Comment by underscorediscovery** [comment]
Actually this came from an incorrectly formatting `<target>` node, never mind the above.

**Comment by hughsando** [comment]
Ok, I think we have a solution.
