### ISSUE TITLE
Name correction for debug libs

### ISSUE THREAD

**Issue by madrazo** [HaxeFoundation/hxcpp#188]
Does project/Build.xml needs the following line to output the debug version of the libs with the correct name?
 set name="LIB_DBG" value="-debug" if="debug" 

Cheers

**Comment by underscorediscovery** [comment]
It would be `${DBG}` by "built in" variable :

https://github.com/HaxeFoundation/hxcpp/blob/master/toolchain/finish-setup.xml#L3-L4

**Comment by madrazo** [comment]
I see!
But is there are reason for using LIB_DBG instead of DBG ?

**Comment by underscorediscovery** [comment]
If you [search](https://github.com/HaxeFoundation/hxcpp/search?q=LIB_DBG&type=Code&utf8=%E2%9C%93) you'll see it's _used_ but it's never defined. 

I suspect maybe @hughsando has a minor typo here, and meant to use ${DBG}. If the variable is not found it just emits `""` so nothing changes and debug builds in the static case are using the same name.

**Comment by hughsando** [comment]
I have some issues with -debug ndlls, and I'm not quite sure how to handle it.
The hxcpp loader code will not actually load a "-debug.ndll" file, so if you create one, it will not get used unless you copy it somewhere to the original name.  By not automatically adding "-debug" you can switch in-and-out of debug mode on a per-ndll basis, and this has worked well for mas as both a user and developer of ndll files.  This was you never accidentally get an out-of-data ndll as you switch between release an debug modes.  Also, some libraries like NME can usually be left in release mode while the user code is debugged, or the other way around.
Given that "-debug.ndll" is not core feature, it is then up to the code that copies files around to decide how it wants to handle extensions.
For a "normal" user - eg, one that does not use openfl similar to build an installer:
haxe -main Main  ...  ->  Release exe, Release libs
haxe -main Main  -debug ...  ->  Debug exe, Release libs
cd $HXCPP/project; neko build.n -debug
-> Debug exe, Debug libs
haxe -main Main  ...  ->  Release exe, debug libs
cd $HXCPP/project; neko build.n
->Release exe, Release libs

Now, if you want the "-debug" so you can move the dlls around using some kind of installer:
neko build.n -debug -DLIB_DBG=-debug
Will generate the files you require, while not confusing developers who do not rename the files.

**Comment by underscorediscovery** [comment]
Yep, that's what I ran into as well. I did try all various manner of solving this but in practice it was better consistently the same file under different configurations.

The % of time a debug ndll is needed is quite low, usually related to active development or the user debugging a crash, in which case their mental model for your dependency tree is incomplete compared to the ndll developer anyway, and it rapidly increases the complexity and thus chance of error, so you'll start to doubt that the information is valid even if it lines up with your expectations, and many times it lines up and your expectations are wrong. Simpler to just remove the chance of that happening in my view.

Even if it did load my-debug.ndll "if it exists alongside" (which I tried) it becomes really cumbersome in short time, because of desync happening where you're debugging the wrong file. 

Consider there are N*M cases, 
`app(rel) lib(rel)` 
`app(debug) lib(rel)` 
`app(rel) lib(debug)` 
`app(debug) lib(debug)`

If you have a third lib, it's N*M*M cases. 
If you can account for the problems stopping you from doing this you will probably turn back because of mental gymnastics - even as the developer with full knowledge of the setup.

**Comment by hughsando** [comment]
Yes, this is exactly my thinking.  So I have left it up to the
meta-developer (eg, lime/openfl) to handle -debug.ndll themselves if they
want.  Nme uses the rebuild-with-debug-to-the-same-name model exactly to
avoid the confusion you refer to.

**Comment by madrazo** [comment]
I see . thanks for the clarification.
