### ISSUE TITLE
AppVeyor timeout?

### ISSUE THREAD

**Issue by Simn** [HaxeFoundation/hxcpp#191]
I'm not entirely sure but it looks like AppVeyor is timing out on hxcpp now: https://ci.appveyor.com/project/HaxeFoundation/hxcpp

Failed 2 hours ago in 39 min 59 sec

**Comment by hughsando** [comment]
Looks like maybe the machine is very slow?  Without some timestamps, it is
hard  to tell if it is a cumulative total, or one of the files hanging.
The cpp test which take 9 seconds on my machine are taking 150 seconds on
the appveyor machine, so it could just be a cumulative thing.

**Comment by Simn** [comment]
Yes, I just saw that run times like that are nothing new. It's usually around 30 minutes but spikes to timeouts every now and then.

Anything we can do about that @andyli?

**Comment by andyli** [comment]
Yes, AppVeyor's builds under the free OSS plan are using pretty slow Azure instances (see https://github.com/ampl/mp/issues/14#issuecomment-57188081).
The hxcpp test is indeed running for 150s - I'm not sure if it is normal. This [page](http://www.appveyor.com/pricing) mentioned that there is only 1.75 GB RAM, so maybe it is due to running out of RAM?

I changed the AppVeyor config from building neko from source to installing 2.0.0. It should now be able to complete in 40 min.

I noticed that @thomasuster has just [requested](http://help.appveyor.com/discussions/questions/453-make-build-timeout-longer) Appveyor to increase the timeout for us. Thanks Thomas! If we are able to use 60min, I think we can activate HXCPP_M64 too.

**Comment by andyli** [comment]
Aargh, the build pass on my fork in 36 min 2 sec but exceeded 40 min here... so the build time is really unstable on AppVeyor...

**Comment by thomasuster** [comment]
Feodor increased the timeout. Could someone with admin give it a kick?

**Comment by andyli** [comment]
Rebuilding now :D

**Comment by thomasuster** [comment]
success!

**Comment by Simn** [comment]
Oh nice, I didn't know the build log had timestamps.

Thanks!
