### ISSUE TITLE
From PTR to array, and the other way

### ISSUE THREAD

**Issue by ncannasse** [HaxeFoundation/hxcpp#216]
I was discussing by mail with @hughsando about being able to get a void\* from an Array on the C++ side, and I'm now stuck having to deal with opposite thing, which is to wrap a void\* + length into an Array object that can be passed into Haxe code.

I think that such facilities are quite necessary when you want to use `__cpp__` without going threw the dynamically typed CFFI.

I would like to see added the following methods:

```
class Array : public hx::ObjectPtr< Array_obj<ELEM_> >
public:
Array( void *data, int dataSize ) { ... } // wrap using an Array_obj<unsigned char> ?
void *GetContentPtr() { ... }
int GetContentSize() { ... }
}
```

**Comment by ncannasse** [comment]
PS: if we can have the same facilities accessible through `cpp.Pointer` then it also allows users to do these things haxe-side

**Comment by hughsando** [comment]
Setting array data is complicated by the fact that it needs to be GC managed memory.  So you can share it between arrays, or allocate it especially for the array, but not set data you get from some arbitrary external data source.
Now, if you are going to allocate it especially, you may as well use the array class itself to do the allocation.  This is basically how the cffi "buffer" works - it uses a callback to create an array, and then uses the data it gets from this.
I could add NativeArray.setData( void *, length, (alloc length) ), but as I say, you need to be sure the memory is GC-managed otherwise you will get a crash at collect time.

**Comment by ncannasse** [comment]
@hughsando in that case the data is allocated by a third party library, so it's managed by the wrapper, either through a finalizer or with explicit dispose() call.
For API reasons, I really would like to expose this data as an Array so it can easily be manipulated as Bytes or other wrapper. Could we have a way to mark such Array as holding a third party ptr and thus skip the mark phase ?

**Comment by hughsando** [comment]
I could maybe derive a "non-marking" array from an array, but it might get
a bit messy, and would have to be careful to only create these for the
array types that need them, not all array types to avoid size blowout.
This would be more manageable and neater API-wise if it were only one
datatype, ie Array<unsigned char>
The other way would be if you could get the memory allocated externally to
be prefixed with the 4 bytes 0xffffffff.

**Comment by ncannasse** [comment]
Sadly I can't guarantee the prefix since I don't control the memory allocation at all. I think we should at least support Arrays of unsigned char and float (single precision) which are the most used for interacting with low level libs

**Comment by hughsando** [comment]
I have added the NativeArray functions setData/setUnmanagedData, eg:

using cpp.NativeString;
using cpp.NativeArray;
using cpp.Pointer;
import cpp.Char;
import cpp.Float32;

class Test
{
   public static function main()
   {
     var a = new Array<Char>();
   a.setUnmanagedData( "Hello!".c_str().inc().reinterpret(), 5 );
   trace(a);

   var a = [1,2,3,4];
   var b = new Array<Float32>();
   b.setData( a.address(0).reinterpret(), 1 );
   trace(b);
   a[0] = 0;
   trace(b);
   }
}

You want the 'setUnmanagedData' version if the data is external.
You must first "new" the array, and then set the data.  This way, you can
also return the data in a parameter array.
This might also be quite handy for aliasing arrays in non-external haxe
code.

Hugh

**Comment by ncannasse** [comment]
Great ! Could we add GetContentPtr() / GetContentSize() as well so I don't have to rely on ArrayBase ?

**Comment by hughsando** [comment]
Well, there is length and address(0) - should do the trick?

**Comment by ncannasse** [comment]
in the C++ side as well ? but is length() the number of elements or the memory size ?

**Comment by hughsando** [comment]
Hi,
Yes, from the c++ side, it is "length" (variable, not function call) which
is number of elements, and
 inline int getElementSize() const;
 inline int getByteCount() const;
 inline char * getBase() const;
If you have a "real" array - that is something other than Array<Dynamic>
(which is really "Dynamic").
Otherwise, you will need to cast the Dynamic to the ArrayBase to get at
these functions.
