### ISSUE TITLE
Using compiler cache

### ISSUE THREAD

**Issue by yanhick** [HaxeFoundation/hxcpp#223]
Hi,
I'd like to use the compiler cache feature to share `.o` files between builds. I was able to make it work using the `HXCPP_COMPILE_CACHE` env variable. 

However, I add to modify the `createCompilerVersion` function in `tools/hxcpp/Compiler.hx` to set `mCompilerVersion` (I hard-coded it to `"1"`). The `mCompilerVersion` needs to be set to activate the compiler cache but it doesn't seem to be set anywhere in the code. Is it a work in progress feature ?

Thanks

**Comment by hughsando** [comment]
What OS are you using?
The compiler version should come from createCompilerVersion, which runs a program to get the compiler version.
The program is specified by the 'getversion' element in the compilers build secion.  For windows this is:
```
<getversion value="cl.exe"/>
```
For mac it is
```
<getversion value="xcrun --sdk macosx${MACOSX_VER} clang++ -v" if="HXCPP_CLANG" />
```
But is not defined for the other platforms.  So I think it might be a matter adding these commands to the various compilers.  Maybe something like "gcc -v"

**Comment by jcward** [comment]
I'd like to help get this working for Linux - let me know what I can do to be helpful.

Given a quick search, here are a few potentially useful "version" commands I found:

<pre>
>g++ --version
g++ (Ubuntu 4.8.2-19ubuntu1) 4.8.2
(copyright info...)

>ldconfig -p | grep stdc++
	libstdc++.so.6 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libstdc++.so.6
	libstdc++.so.6 (libc6) => /usr/lib/i386-linux-gnu/libstdc++.so.6
</pre>

What all programs / libraries are we trying to detect changes in?

Since you're hashing the output, you could maybe run both commands:

    <getversion value="g++ --version; ldconfig -p | grep stdc++" if="HXCPP_CLANG" />
