### ISSUE TITLE
CrystaX NDK support

### ISSUE THREAD

**Issue by JeriXNet** [HaxeFoundation/hxcpp#227]
There is nice vanilla compatible ndk out there: [crystax.net](https://www.crystax.net/)
I've tried using it by quickly modifying(hacking) android-toolchain.xml and it worked!
Problem is I don't know how to add support of this ndk properly. First thought was to create new toolchain for android that will be invoked with some flag like `-crystax`

**Comment by hughsando** [comment]
Crystax was actually the first (and only) ndk suported by hxcpp before the
official android NDK thought that people might actually want to use
exceptions.  So I respect it a lot.

Typically, this kind of selection would be done with either a "-D crystax"
call on the haxe command line, since these defines are passed on to hxcpp,
or a HXCPP_ variable set in the .hxcpp_config.xml file.

If you have a look at how

tools/hxcpp/BuildTool.hx
handles the "cygwin" target - it sets the toolchain and bindir.  The
toolchain will cause the loading to the named file from the toolchain
directory.  You can copy and modify one of the existing toolchain files.

This is a basic outline - enough?

**Comment by JeriXNet** [comment]
Thanks! I will try it like this.

**Comment by JeriXNet** [comment]
Something like this? https://github.com/JeriXNet/hxcpp/commit/6b5aca8ec59f4b78000b7dd5e136fed5a18b67c3
