### ISSUE TITLE
obj path and file names sometimes too long for win7

### ISSUE THREAD

**Issue by Justinfront** [HaxeFoundation/hxcpp#233]
Hi Hugh

Rather an obscure issue here feel free to close if beyond scope.

Hi I had a rather strange issue on a project where the obj file silently failed to be created on windows 7.

This file
04e3d618_BalancedBSTNode_phoenix_geometry_GeometryKey_phoenix_geometry_Geometry.obj

was not created in 
C:\projects\currentProjects\experimental\other\old\addCurveTo\hxDaedalus-luxe-examples\hxDaedalus-Luxe-Examples\07-MeshExtractionFromBitmap\bin\windows.build\cpp\obj

The solution was to move the project to a shorter path, it's a crazy error for the average user to find (and took me awhile).  I wonder if hxcpp could tell the user when an object file fails to be generated for this reason, or if hxcpp can auto reduce suitably long names at compile or use a different copy method or....? .  I know it's not really hxcpp problem but since the error to write the obj file is silent it makes for a very obscure bug that is likely to fox most people and certainly to take quite some time for them to find.  It may well not effect windows8, but I don't think it's easy to get an update fix on windows7.

Best Justin

**Comment by Simn** [comment]
In theory the directory path itself could be so long that there's no viable file name to use. It might still make sense to detect this and give a proper error message.

**Comment by gamicklisafisher** [comment]
For deletion or handling of long name i check that "Long Path Tool" software should be try, many articles refer this for such solutions.

**Comment by hughsando** [comment]
There seems to be some issues with ocaml and total path length (windows 10).
 haxe -main Test -neko lllllooooooooooogddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppgg.n

gives:
Sys_error("lllllooooooooooogddddddddddddddddddddddddddddddddddddddddddddddgggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggggppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppgg.n: No such file or directory")

And deeper in the directory structure you go, the worse it is.  Maybe  MAX_PATH=256.
I could potentially calculate the length of the dir + obj and do a warning so that it is not hxcpp  pushing it over the edge.  Or hash the obj name if it is longer than X (the dir path  is already hashed)
Not really sure what to do about this.

**Comment by hughsando** [comment]
I'm not sure there is much I can do about this one.
