### ISSUE TITLE
GC deadlocks, crashes

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#303]
Below is a sample program [1] that stresses the allocator from many threads which seems to reliably hit a problem in the GC. Initially thinking it was a race condition with the new thread pool code, but that is only conjecture at this point. The problem manifests itself as deadlocks in a few different ways, and have also seen a crash in marking code [2] while the non-GC threads are all busy waiting in GlobalAllocator::GetFreeBlock [3].

Tomorrow I plan on investigating the deadlocks further and posting details on where those are happening, but this sample program should be reliable enough to allow more eyeballs on this issue.

This was tested on Windows and have not tested the HX_GC_PTHREADS path.

[1] https://github.com/james4k/hxcpp-issue-gc-deadlock
[2] https://github.com/HaxeFoundation/hxcpp/blob/5373d3b7b9a5d58bf2aaee70afca5690ba4f85de/include/hx/GC.h#L283
[3] https://github.com/HaxeFoundation/hxcpp/blob/5373d3b7b9a5d58bf2aaee70afca5690ba4f85de/src/hx/gc/Immix.cpp#L2105

**Comment by james4k** [comment]
OK, I just saw https://github.com/HaxeFoundation/hxcpp/commit/dc950dbe0ac379494695fc3ca592b3b3e600f63f

Testing this change now.

**Comment by james4k** [comment]
Alright, that change seems to be unrelated to the deadlocks I am experiencing.

**Comment by hughsando** [comment]
There was a bug (thanks for the example) that shows up when 2 threads try
to collect at the same time.
The fix seemed to work here - please close the issue if you are happy its
working for you too.

**Comment by james4k** [comment]
No, I still see problems.

**Comment by james4k** [comment]
If it works fine for you, I need to check if there is anything going on with a merge on my side. It is late for me now, though, so will continue this tomorrow.

**Comment by james4k** [comment]
Oh, I'm sorry. I misunderstood. You were referring to https://github.com/HaxeFoundation/hxcpp/commit/c81ac4c85b55434be60dad285dc66a8d823ee470

Thanks, that seems sound. Will test tomorrow!

**Comment by hughsando** [comment]
I have tried to clean up the logic a bit for the case when 2 threads try to
collect.  Hopefully this makes it a tiny bit faster too.

**Comment by ex** [comment]
I think this issue is related to the issue we found in our project.
Unfortunately, testing the latest version with the suggested changes is still showing the hang, but in a different part now: 
`MarkChunk *pushJob(MarkChunk *inChunk)`
`MarkChunk *reult = allocLocked(); <- hangging here`
But maybe I'm doing something wrong and my hxcpp version is not OK. 
Is there some way that we can access the latest hxcpp version that you are testing?

**Comment by james4k** [comment]
It seems that all is well with the latest changes. :)

@ex: see the `haxelib dev` command for using the git version of hxcpp.

Thanks, Hugh!

**Comment by ex** [comment]
@james4k 
Can you test my new test case? 
It's here: https://github.com/ex/haxe/tree/master/timer
I tested your crash simple test with and without the latest hxcpp fixes and I couldn't get it to crash on my end. 
However my project is still crashing on the GC, but in a different part, so I created a new test case that is crashing on my end most of the time (it didn't crashed one of 3 times I tested, so I guess is kind of random, could you test it more times if it don't crash the first time?)

**Comment by james4k** [comment]
OK, @ex

I do get a crash but it seems to be the process running out of memory. At
least for me, running Windows where the default build is 32-bit. Does this
sound plausible?

**Comment by ex** [comment]
@james4k I output a trace every 1000th object is created and the process crashes after only 10000 objects on my end (sometimes), these objects don't must be consuming much memory anyway.
The memory graphs on my computer show very little usage (it has 8 GB) so I don't think is a out of memory crash.
I'm using procdump to debug the crash and the crashing code is inside lmmix.cpp file:
```
    void Process()
    {
       while(true)
       {
          if (!marking || !marking->count)
          {
            
          }

          while(marking)
          {
             hx::Object *obj = marking->pop();
             if (obj)
             {
                block = (char *)(((size_t)obj) & IMMIX_BLOCK_BASE_MASK);
                obj->__Mark(this);  <-- CRASHING HERE
```

**Comment by james4k** [comment]
OK, I wasn't able to reproduce that crash.

**Comment by james4k** [comment]
And to elaborate, I saw the out of memory crash at something like 35000 objects, and the process was using nearly 2 GB of memory which will be the limit for 32-bit builds.

**Comment by ex** [comment]
@james4k ah that makes, sense, I'm testing in a 64-bit system.
But something seems wrong here, because if you check the Dummy objects itself hold only an array with like 10 little objects that hold itself only one integer and one string. So every object must not consume so much memory lets say 1k per object (that's a lot actually) and 35000x1000 = 35 MB.

Of course every time an object is created, every object reads and parses an XML, (this is nuts) but I'm using it because I noticed how stressing for the garbage colector was parsing XML files.

**Comment by ncannasse** [comment]
@hughsando looks like a good stresstest for GC :)

**Comment by hughsando** [comment]
There was a bug (just fixed, but not causing the crash) where the free
memory did not expand correctly, which made the run slower and slower.
There is something funny going on because it does indeed use something like
1.4Gig.
Which looks to me like the xml file is getting held onto on a per-instance
basis, which could be a bug.  I guess if there is a bug, it could also be
related to the crash.

**Comment by ex** [comment]
@hughsando creating objects without reading an XML I can have like 2000000 object consuming 1.6 GB.
But reading the XML I can have like 20000 for the same memory and the process gets slower and slower. I moved the XML reading out of the constructor and nullified the references (just in cargo cult spirit) but it's the same result. If something is leaking memory I think is inside the iterators code or the XML code.

**Comment by hughsando** [comment]
I was getting 200K objects for 1.6 G with xml reading. The bug fix a did a
couple of days ago fixed the speed for me, but this is still not great.
The problem seems to be fragmentation of the row-based memory when reading
the xml because it allocates a small object (the DummyObject containter, or
the param string) which it keeps, followed by a bunch of small objects (the
xml/xml iterators) which become garbage.  However, they occupy the same
logical unit of RAM as the kept stuff, so they all get kept.  This is
pretty unlucky, but obviously repeatable.
I need to get memory defragging working properly to fix this.

**Comment by james4k** [comment]
Maybe I am not seeing something, but it seems odd for a bunch of allocations of the same sizes to cause such fragmentation. A potential bug in the allocator/reclaim?

**Comment by ex** [comment]
@james4k are you going to re-open this issue? I removed openfl from the stress test here: https://github.com/ex/haxe/tree/master/gc.
If you would prefer I can open another issue with this new stress test. 
I'm still seeing the same slow down and memory consumption using the latest hxcpp.

**Comment by thomasuster** [comment]
fyi, there was a diff issue for deadlock on android that was fixes with this. What's your targets? https://github.com/HaxeFoundation/hxcpp/commit/ff2fa804215fa58707011c7fbaffee372004a628

**Comment by james4k** [comment]
@ex, your problem is different, so opening a new issue sounds good to me.

There were some recent GC changes that might address your problem, but will need HXCPP_GC_MOVING defined.
