### ISSUE TITLE
Cppia crashes when calling an interface function that was defined in the host

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/hxcpp#374]
I'm sorry I can't create a reproducible issue about this right now, so please let me know if the information I give you here is enough to fix it:

I'm getting a hard crash at `hx::CallMemberVTable::runVoid`, inside the `CALL_VTABLE_SETUP` macro.
Investigating further leads me that `__GetScriptVTable()` is returning a null pointer. The type that is returning a null pointer is a `IMyInterface_delegate_<SomeTypeDefinedInTheHost_obj>`.
Looking into the generated hxcpp source code for delegates, it doesn't seem that `__GetScriptVTable()` is indeed overridden.
I'm not sure if it should be in this case, since this is defined by the host entirely.

Please let me know if you need a reproducible case, and I'll work on it

**Comment by waneck** [comment]
On a related note, it would be great to have a simple extern c function that prints a backtrace. These kinds of crashes could be much easier pinpointed with a debugger like gdb if we could get a comprehensible backtrace of it :)

**Comment by hughsando** [comment]
The interface stuff is a little tricky -  on hxcpp because  I get the c++ compiler to do some work to convert between the type and its interface pointer, and in cppia I use a "negative vtable" which works out very easy.  However, where there is cross-over things must be done manually between hxcpp/cppia, so I may have missed something.
You can do  some native debugging  (at least as far as a call-stack goes) if you compile the host and cppia with debug flags.
![cppiastack](https://cloud.githubusercontent.com/assets/1665494/13040659/f3eaa202-d3e9-11e5-9f28-d6b7746aa801.png)
Here you can see the filename, function and line number of the breakpoint.  But I guess you are after something a bit more automated?

**Comment by hughsando** [comment]
I have recently changed the interface implementation code in hxcpp/cppia, and I think this might be fixed now.
