### ISSUE TITLE
cpp.vm.Gc.run(true); windows vs linux (travis)

### ISSUE THREAD

**Issue by wighawag** [HaxeFoundation/hxcpp#383]
As part of gcusage (https://github.com/wighawag/gcusage) I rely on Gc.run(true) to gather allocation and deallocation data. on travis some of my assert on deallocation and bytes used differ from my local test (on windows). It seems on travis(linux) the Gc.run(true) have no instant effect while on windows it does effect instantly and I can see the deallocations. 
Any idea why, could this be fixed?
Thanks

**Comment by hughsando** [comment]
The conservative nature of the GC collections means that different
compilers (or versions of compilers, or optimization flags) can cause
certain objects to live longer than strictly required.

The best way I have found of testing this so far is in:
https://github.com/HaxeFoundation/hxcpp/blob/master/test/haxe/gc/TestGC.hx#L22

Things to note:  Call gc run from a different function than the one doing
the allocation, otherwise temporary registers can hold references.
The "clearStack" call just pushed a bunch of zeros around.

Again, this is not guaranteed to work, but you may be able to construct a
reliable test.

**Comment by wighawag** [comment]
Thanks, It helped to have almost the same between linux and windows + allow me to get the bytes used temporarly.

The issue left relate to the temporarly used bytes (the one that was allocated but deallocated right away). on Linux here : https://github.com/wighawag/gcusage/blob/master/Tests/src/TestAll.hx#L90 I get more bytes.

Any idea?

**Comment by hughsando** [comment]
Not sure about this one - as I have said, gc tests can be a bit funny.
But it might be a 32/64 bit thing?

**Comment by wighawag** [comment]
That was it : 32/64 bit. Thanks
