### ISSUE TITLE
cpp.Pointer improvement suggestion

### ISSUE THREAD

**Issue by delahee** [HaxeFoundation/hxcpp#386]
@hughsando 

Hi !
I may have mistaken something but at some point, we should add : 

```
cpp.Pointer.toUnmanagedArray( ptr : cpp.Pointer<T> ) : Array<T>
cpp.Pointer.toUnmanagedVector( ptr : cpp.Pointer<T> ) : haxe.ds.Vector<T>
```
In order to make going back and forth pointer easier.

This would help write bindings and write very efficient code hxcpp...or have I missed something ?

I saw there are array accessed and stuff like that but with the effort we put in NativeArray.* we could get a significant boost in processing power, couldn't we ?

cheers,

**Comment by delahee** [comment]
In fast maybe we could step a bit further and add haxe.io.Bytes<->cpp.Pointer transtyping functions too ?

**Comment by hughsando** [comment]
The most efficient array access is actually via Pointer.at(index), which maps directly to c++ pointer access.  This is a bit  better than array, since you can offset the pointer (incBy etc).

Going back to Array is most useful when dealing with code that is already using arrays (eg, written with other targets in mind).

BytesData is actually an array in c++, so you can use "ofData" / Pointer.ofArray to go backwards and forwards.

I should reiterate that you need to be careful of GC references.  You can't use a pointer to the middle of an array unless the array is natively allocated, or the base pointer is also on the stack, which is not strictly the case in the example below when I use "incBy(3)".

```
     var bytes = haxe.io.Bytes.ofString("some String");
     var ptr = Pointer.ofArray(bytes.getData());
     trace(ptr.at(1));

     ptr.incBy(3);
     var bytes = haxe.io.Bytes.ofData( ptr.toUnmanagedArray(5) );
     trace( bytes.toString() );

     var array = [1.1, 1.2, 1.3];
     var ptr = Pointer.ofArray(array);
     ptr.setAt(1,1);
     trace(ptr.at(2));
     var unmanaged = ptr.toUnmanagedVector(3);
     trace(unmanaged);
```
