### ISSUE TITLE
Cast resolve wrong native name

### ISSUE THREAD

**Issue by ibilon** [HaxeFoundation/hxcpp#406]
This code:
```haxe
class Test {
	public static function main () 	{
		var s : Dynamic = XRef.create("test");
		caster(s).destroy();
	}	
	public static inline function caster (s:Dynamic) : XRef {
		return cast s;
	}
}

@:include("string")
@:native("cpp::Reference<std::string>")
extern class XRef extends XImpl {
	@:native("new std::string") public static function create(text:String) : XRef;
}

@:native("std::string")
extern class XImpl {
	@:native("delete") public function destroy () : Void;
}
```

Create this error:
```
Error: ./src/Test.cpp: In static member function ‘static void Test2_obj::main()’:
./src/Test.cpp:30:34: error: conversion from ‘Dynamic’ to ‘const char*’ is ambiguous
 HXLINE(   6)  ( (::std::string)(s) )->delete();
```

Disregard the ambiguity, I just wanted to make a small test case,

it should be ` ( (cpp::Reference<::std::string>)(s) )->delete();` and not ` ( (::std::string)(s) )->delete(); ` since it cast to `XRef`.

The classes I deal with (wxWidgets) can't be copied, so that's important to only use the references.
And in my case it's not with `Dynamic` but a parent class type.

Same error with safe cast.

**Comment by hughsando** [comment]
This is a tricky one, because hxcpp thinks that in order to call "destroy", it only needs an "XImpl", not a "XRef", so it is casting to an "XImpl" (std::string), not a XRef("cpp::Reference<std::string>")
The fix is to move the native destroy to the XImpl class.  (ie, you can delete the reference but not the structure)
The other issue is the name of the destructor.  For string, this is a bit ugly "std::string::~string"
Lastly, the native declaration of new tells haxe it is a XRef, but it is not.  Then assigning it directly to a Dynamic breaks.  hxcpp does not know that it is not actually XRef yet.  I'm not sure of the best way of handling this, but this example works using a temp variable.  Maybe an explicit cast would work,:

```
@:cppFileCode("using namespace std;")
class Test {
    public static function main ()  {
        var s : XRef = XRef.create("test");
        trace(s);
        trace(s.c_str());
        var d:Dynamic = s;
        caster(d).destroy();
        trace("ok");
    }   
    public inline static function caster (s:Dynamic) : XRef {
        return cast s;
    }
}

@:include("string")
@:native("cpp::Reference<std::string>")
extern class XRef extends XImpl
{
   @:native("new std::string") public static function create(text:String) : XRef;
   @:native("std::string::~string") public function destroy () : Void;
}

@:native("std::string")
extern class XImpl {
   // Some function ...
   public function c_str() : cpp.ConstCharStar;
}
```

Depending on where you get your native pointers from, something like this should work:
```
@:include("string")
@:native("cpp::Reference<std::string>")
extern class XRef
{
   inline static function create(text:String) : XRef { var x: XRef =  cast callNew(text); return x; }
   @:native("new std::string") static function callNew(text:String) : Unknown;
   @:native("std::string::~string") public function destroy () : Void;
   public function c_str() : cpp.ConstCharStar;
}

extern class Unknown { }
```

**Comment by hughsando** [comment]
I'm going to close this - please reopen it if this does not make sense.
