### ISSUE TITLE
"HXCPP_ALMOST_SILENT"?

### ISSUE THREAD

**Issue by Gama11** [HaxeFoundation/hxcpp#413]
`HXCPP_QUIET` and `HXCPP_SILENT` are great additions, but it would be useful to have something in between that only outputs errors (quiet still outputs a line for each compiled file, which is still a little verbose, and silent is not really usable on CI for me because it suppresses errors as well). For Travis, I'm basically only interested in build failures.

Not sure what a good name for that would be.

**Comment by hughsando** [comment]
I think silent can output error, since there will never be any from hxcpp
:)  (in normal usage) so the name can stay.  In fact, in the error case we
still want to be quite verbose (maybe even retrospectively adding some
output)
In quiet/silent cases need to make sure the command-line that generated the
error is also printed.
I'm also thinking about printing the common build-flags once only, then
printing the .cpp names as it goes and making this the default. possibly
with a counter of keep people awake : MyClass.cpp (12/1231).
This gives me what I need when I go over a users paste-bin - to look at the
include path and api level.

So:
  silent - errors only
  quiet - adds file-group debug
  new normal = adds 1 small line per file
  verbose = same as verbose is now (full compile lines, makefile/setup
debug, banner)

Removing the travis hack would be fine

**Comment by Gama11** [comment]
Sounds good to me - especially making he default output less verbose seems sensible. :)

**Comment by hughsando** [comment]
I have adjusted the verbosity settings - should be good now.
