### ISSUE TITLE
Installed MSVS 2015 update, now I can't compile with any version of MSVS

### ISSUE THREAD

**Issue by hedgehog90** [HaxeFoundation/hxcpp#436]
I had MSVS 2015 and I was able to compile, but since updating now I'm getting process creation failure : cl.exe every time no matter which version I use unless it's in debug mode.
VS140COMNTOOLS is correctly pointing to Common7\Tools\
I've tried disabling the other environment variables (120, 110 and 100) but no change.
My OS is Windows 10 64bit.

**Comment by hughsando** [comment]
So mscv15 was working, not it's not? They may have moved something in the update I guess.
If you compiler with hxcpp verbose mode (-D HXCPP_VERBOSE if you are using the the github version of hxcpp, otherwise set the environment variable) it should print some stuff at the top about how it is looking for the setup.
If msvc was never working, if could be that you missed the "install c++ tools" option on the installer.

**Comment by hedgehog90** [comment]
I ran the installer again and added C++ tools. For some reason running the update a few days ago removed this.
Thanks for the suggestion, all is working fine now with MSVC 2015. The build failure with the other versions of MSVC were unrelated, on closer inspection HXCPP was building correctly but a post build command was screwing up the final step.
Anyway, this works so I'm happy :)
