### ISSUE TITLE
 Error building

### ISSUE THREAD

**Issue by mboussaa** [HaxeFoundation/hxcpp#438]
I get this message when I execute neko build.n
neko run.n Build.xml -Dlinux -DHXCPP_M64  /hxcpp/project/
Error: Could not find build target ""

**Comment by andyli** [comment]
Looks like you're using a haxe nightly build. The error is likely caused by the [Sys.command and sys.io.Process changes](https://github.com/HaxeFoundation/haxe/wiki/Breaking-changes-in-Haxe-3.3.0#syscommand-and-sysioprocess). I've fixed the hxcpp build tool some time ago, so please get the git version of hxcpp and rebuild the hxcpp build tool according to https://github.com/HaxeFoundation/hxcpp#building.
