### ISSUE TITLE
error C2275: 'cpp::Pointer<Int>': illegal use of this type as an expression

### ISSUE THREAD

**Issue by dfadev** [HaxeFoundation/hxcpp#456]
The following doesn't compile:  (related to #448)

```
var z = [ 1, 2, 3 ];
var p:Pointer<Int> = cast untyped __cpp__("{0}", NativeArray.address(z, 0).ptr);
```

**Comment by hughsando** [comment]
Yes, anything with ```__cpp__``` in it is not guaranteed to work - the onus is on the writer to make sure it does.  The problem is that the NativeArray call is doing some inlining and so is a series of expressions, rather than a single one, and you can't cast a series of expressions.
Any of the following should work though:
```
var tmp = NativeArray.address(z, 0).ptr;
var p:Pointer<Int> = cast untyped __cpp__("{0}", tmp);

var p:Pointer<Int> = cast NativeArray.address(z, 0).ptr;
var p:Pointer<Int> = NativeArray.address(z, 0);
var p = NativeArray.address(z, 0);
```
