### ISSUE TITLE
hxcpp build tool does not recompile all source files when headers are changed

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#465]
When a header file is changed, hxcpp does not seem to recompile source files including that header file. This means that when I change some header file, I need to rebuild all source files to update, which is sometimes pain to do. Is this difficult to implement?

When building from Haxe, hxcpp only recompile files that are changed from previous build. Is this difficult to do when I build lime.ndll from existing Build.xml?

**Comment by hughsando** [comment]
You need to explicitly add the dependencies to the build.xml files.
eg:
https://github.com/haxenme/nme/blob/master/project/ToolkitBuild.xml#L165

**Comment by vroad** [comment]
So I should add dependencies to all lime source files...?

Will this be fixed? I think C++ compilers have a way to report all header files, and other tools are using that information.

**Comment by hughsando** [comment]
It is pretty easy just to add all the headers - given that they don't change that often.  I am unlikely to automate this in the near future - you could look at automating it for lime with some "mkdeps" tool, and  I would consider a PR for the hxcpp tool, but it is not a priority for me.  The hxcpp compiler cache combines the compiler version with the contents of the explicitly listed dependencies - this way it can avoid checking the contents/timestamp of the system include files. 
The hxcpp generated code has proper dependencies for the generated header files because it knows what is going on.
