### ISSUE TITLE
src/Dynamic.cpp: Int64Data dynamic_cast wrong type

### ISSUE THREAD

**Issue by james4k** [HaxeFoundation/hxcpp#486]
Looks like a  copy-paste bug in Int64Data, where the `__Is` method dynamic_cast's to `DoubleData *` to check the type, when it should be casting to `Int64Data *`.

https://github.com/HaxeFoundation/hxcpp/blob/23b0726c020623fba5368b4c70bccc033474fc73/src/Dynamic.cpp#L142

The `__Compare` method also looks suspect:

https://github.com/HaxeFoundation/hxcpp/blob/23b0726c020623fba5368b4c70bccc033474fc73/src/Dynamic.cpp#L151

**Comment by hughsando** [comment]
The ```__Is``` is indeed a typo.  But I not actually sure where this method is used - I think the fix might be to remove all the ```__Is``` functions.
Compare is a bit more tricky, since Comparing Int64 1 with double 1.1 should give a less than.  And I probably need to do something the other way around when comparing large doubles with large Int64s too.

**Comment by james4k** [comment]
Just came across an issue with `Int64Data` using a `double` value for storage (lost precision). What is the reason for not using `cpp::Int64`? Is the `vtInt64` object type supported?

**Comment by hughsando** [comment]
The problem with vtInt64 is that there is no real support for it in the haxe "Type" class, and as I say, some things like compare need attention.
But you are right, it should be stored as an int64, even with this.

**Comment by hughsando** [comment]
Int64 now has its own Type.
