### ISSUE TITLE
hxcpp sometimes collects objects allocated inside NDLL too soon, when large amount of memory is allocated inside NDLL

### ISSUE THREAD

**Issue by vroad** [HaxeFoundation/hxcpp#521]
I'm getting reports from @jgranick that hxcpp sometimes collects objects allocated with `alloc_empty_object()` too soon when large amount of memory is allocted inside NDLL (e.g. when returning images/audio data decoded in NDLL to Haxe). He said this occued on iOS and some other devices, but I'm not sure if this is specific to some devices.

Will `AutoGCRoot` or `gc_safe_point()`help in solving this issue?
I've found this in http://old.haxe.org/doc/cpp/ffi?version=8189 , but not sure when I should use this.

For now we are avoiding this issue by allocating objects in Haxe side (Avoiding the use of `alloc_empty_object()`).

**Comment by hughsando** [comment]
Depending on what the issue is, AutoGCRoot may fix the problem.
There are a few things that might be going wrong.
The stack scanner needs to be able to find the variable on the stack - eg, as a local variable or function parameter.  If you store the value in a member variable of some heap-allocated structure, the collector will not be able to see it.
Now it is possible, although unlikely, that the compiler will optimize-away the reference somehow.  In this case, and AutoGcRoot would solve the problem, but I would look elsewhere first.
It should also be easy enough to test - if you add a finazlier to the object and then call into haxe to a function that explicitly runs the gc, you should be able to see if the finalizer get called or not.
Since you mention audio, it is worth also considering your thread handling.  There is a recent discussion on this point on the google group.  https://groups.google.com/forum/#!topic/haxelang/V-jzaEX7YD8

If you can refer to the suspect code, I could have a quick look to see if anything sticks out.

**Comment by vroad** [comment]
I don't think audio thread is involved here, because in current version of OpenFL audio thread is created by OpenAL, not by Haxe.

He said passing output object to classes like ImageBuffer fixed GC issue.

`lime_image_load` is a lime CFFI function that loads images from file/memory and returns decoded data.

https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/graphics/ImageBuffer.cpp
https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/ExternalInterface.cpp

**Comment by hughsando** [comment]
It would appear you are not using a GC root to hold onto the 'value' : https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/include/graphics/ImageBuffer.h#L37

This is the case I mentioned earlier about a GC value being stored in a heap-allocated member variable.

The current implementation also has issues if the developer uses "HXCPP_GC_MOVING" garbage collector, since the GC does not know that you have stashed a pointer in your structure.

**Comment by vroad** [comment]
@jgranick is using pass by pointer here for some reason, but ImageBuffer itself is held on stack. So it is visible from GC until function call finishes, isn't it?

https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/ExternalInterface.cpp#L743

**Comment by vroad** [comment]
Maybe local variables are optimized away as you mentioned? Or is the problem in elsewhere? He thinks changes in this commit fixed the issue.
https://github.com/openfl/lime/commit/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7

**Comment by hughsando** [comment]
You are right - it does look like a stack value.
The "data*" member looks a bit suspect though.  You do not have an
"operator=" on that class so it could copy the data pointer to the new
instance, then delete the data pointer as the first object destructs, and
then delete it again once the second (copy) object destructs.  But this
would not explain GC issues - might just be a different issue.
This is the rule of 3 - if you have a non-trivial destructor (as you do),
you could also implement (or hide behind "private") the copy constructor
and operator= to avoid accidents.  This goes for the AudioBuffer commit you
reference too.

The code as I see it "should" work I think.  If it does not, then I think
it is worth getting to the bottom of, otherwise I would be concerned that
the issue may pop up again if GC_MOVING is enabled.

**Comment by vroad** [comment]
If compiler optimization is the cause of this issue, then turning off optimization may temporary fix the issue, but I don't have iOS devices to test.

Is static linking relevant to this issue? I've heard that iOS does not allow dynamic linking.

**Comment by hughsando** [comment]
Also note that initializing mValue=0 is not right on neko, it should be
alloc_null()

**Comment by hughsando** [comment]
Also note that the ImageBuffer has a pointer to "data" and the data has a
mValue.
There are no GC references to the mValue, since "data" is allocated on the
heap, and that could well be your problem.

**Comment by vroad** [comment]
Allocating Bytes/ArrayBufferView on heap might be the cause of the issue as you said. GC cannot see it if it's on heap. Let us check if that fixes the problem.

https://github.com/openfl/lime/blob/a9bed580b337529e517ee432c2ea41d1c00aab49/project/src/graphics/ImageBuffer.cpp#L97
https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/graphics/ImageBuffer.cpp#L114

**Comment by vroad** [comment]
Well `Bytes` is allocated on heap, but looks like its value is protected by AutoGCRoot. Or, should we obtain value from AutoGCRoot every time to avoid GC issues?

Older Bytes.cpp: https://github.com/openfl/lime/blob/bb6465fd385ddcd030b7c7a002b495be9c5eeff2/project/src/utils/Bytes.cpp#L174-175
Newer Bytes.cpp: https://github.com/openfl/lime/blob/eb11502ecd98fb03d5ccc5f76c7f7387d90f7fe7/project/src/utils/Bytes.cpp#L180-L181

**Comment by hughsando** [comment]
Not sure which commit I should be looking at, but this value in head is
unprotected:
https://github.com/openfl/lime/blob/develop/project/src/utils/ArrayBufferView.cpp#L131

The GCRoot code you show is mostly right (as right as storing the reference
in haxe, like the big commit you referenced), but could still be an issue
if HXCPP moves the memory associated with _value.  You should simply remove
_value as a member and always get it from the GC Root as you suggest.

**Comment by hughsando** [comment]
You should also do private copy/constructor (no need to implement these function) to avoid cutting yourself:
```
struct ImageBuffer
{
   SomeClass *buffer;

   ImageBuffer() : buffer(0) { }
   ~ImageBuffer() { delete buffer; }

private:
   ImageBuffer(const ImageBuffer &);
   void operator=(const ImageBuffer &);
};
```
Make sure you do not accidentally assign the buffer member and then delete it twice

**Comment by vroad** [comment]
Simply allocating Bytes/ArrayBufferView on stack may also solve problems. I'm not sure why it's currently allocated on heap. I'll also consider implementing private copy constructor.

**Comment by vroad** [comment]
I could make my test app crash by inserting a loop that allocates lots of buffers with `alloc_buffer_len()`. Crash occurs both on Android and Windows. I inserted the loop between `alloc_empty_object()` and first `alloc_field` call in `ArrayBufferView.cpp`. `alloc_field()` call failed because `arg1.__vfptr' was already null. That means `ArrayBufferView.mValue` is prematurely corrected, doesn't it?

The loop didn't made my app crash if I allocate everything on stack, so I bet your guess is right. Then, this is probably not a hxcpp's bug.

**Comment by ncannasse** [comment]
@hughsando are you checking the registers ? on x86-64 you might have several registers that store allocated objects but are not visible on the stack

**Comment by vroad** [comment]
@ncannasse I'm not sure if that's related as I only checked x86 and armv7.

Here mValue belongs to a heap allocated class instance, so it's not strange to get a crash when GC occurs, is it?

**Comment by hughsando** [comment]
The mValue is certainly an issue unless you have a stack object.

Nicolas, I check the registers according the the spec as far as I can tell,
https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/gc/GcRegCapture.cpp#L42

There is a chance that the compiler could store and offset to a gc value
(eg, array iteration), but for the cffi case, the values are opaque, so
this should not be an issue.  It is also possible the preserved  registers
slip the the crack at the top of the stack when the capture function is
called, but I think I have nailed down these issues.
