### ISSUE TITLE
LessThanEq Null<Int> != 5 returns false

### ISSUE THREAD

**Issue by rushmobius** [HaxeFoundation/hxcpp#538]
The fall through logic for LessThanEq comparison for the following is incorrect
var a:Null<Int> = null;
var b:Int = 5;

if (a != 5)
{
// the comparison actually returns false due to the numeric with a object returning false
// the logic should be
// return LESS ? (false) : ((traits1::isNull(v1) && traits2::isNull(v2)) ? EQ : !EQ);
}

**Comment by hughsando** [comment]
Should be fixed by https://github.com/HaxeFoundation/hxcpp/commit/d27ceebf7972c52474ce86ae9dd7c3d51614b615

The 'LESS' does not to matter by convention.  Any lessthan or greaterthan comparison with null will depend on only the "==null" bit.

The code is now the same as the object-object comparison.
Thanks for reporting.

**Comment by hughsando** [comment]
Actually, you are right - the LESS comes into in the less=false,eq-false case.
