### ISSUE TITLE
Cppia failure when host-derived types implement a cppia interface

### ISSUE THREAD

**Issue by waneck** [HaxeFoundation/hxcpp#587]
The code at https://gist.github.com/waneck/5dce5a14064a62b6be4b33905ccd3720 segfaults on latest hxcpp.

As far as I could understand, the issue is that interface slots are negative, which work correctly when a type was fully created by cppia. However, if that type derives from the host (like in this example, Test extends Main), this negative vtable slot is non-existent, which makes it access an unbound array position.

**Comment by waneck** [comment]
This might be a regression. Looking at the code at https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/cppia/CppiaClasses.cpp#L1135 , makes me suspect of this being a regression as well. It seems that right now, if HXCPP_API_LEVEL >= 330, nothing is done if `native` is null ( at https://github.com/HaxeFoundation/hxcpp/blob/master/src/hx/cppia/CppiaClasses.cpp#L1144 )

**Comment by waneck** [comment]
Scratch that, sorry. I just realized that they are handled afterwards, at `link`

**Comment by waneck** [comment]
So it seems that the problem is with the interface's `CppiaClassInfo::getScriptVTableOffset`. Because the interface is created by Haxe (and thus it has no `haxeBase`), it returns `sizeof(hx::Object)`, which doesn't work if the type has a haxe-created super class

**Comment by hughsando** [comment]
I have started some tests for this sort of thing in https://github.com/HaxeFoundation/hxcpp/tree/master/test/cppia
This should make it easier to create a test case, and keep it working.
Without looking too closely,  cast(Test.test, ITest) should just be Dynamic as far as cppia is concerned - it is the Test instance, since interface delegates no longer exist.  Querying the script vtable should be null, since Test is host-implemented, and it should fall back to name (dynamic) lookup.  The "sizeof(Object)" looks like the interface delegate and seems it is not falling back.
I will have to have a look at this.

**Comment by waneck** [comment]
I think it's typed correctly. This still crashes if we set a temporary variable with type `ITest`. But I understand like 20% of what's going on there, so my PR might just be wrong.
But as far as I understand, the issue is really that the vtable address was wrong - and that PR seem to fix it.

I'll add a test case there. Thanks!

**Comment by hughsando** [comment]
Closed by https://github.com/HaxeFoundation/hxcpp/commit/72187839359e250636c8518457acfb05d0adb402
