### ISSUE TITLE
The FileSystem.readDirectory() will be crash in other thread

### ISSUE THREAD

**Issue by fym201** [HaxeFoundation/hxcpp#84]
I use the Thread.create() start a new thread and call FileSystem.readDirectory() in it , the app crashed follow error:    Critical Error: GCFree Zone mismatch

**Comment by leolannenmaki** [comment]
I think we are running to the same issue here.

The only error I get is `Critical Error: GCFree Zone mismatch`. My error happens when booting up an OpenFL app and initializing Google Analytics lib while reading save files.

If using OpenFL, the `haxe-ga` analytics lib uses something called `flash.net.SharedObject` to create a file called `C:\Users\USERNAME\AppData\Roaming\Company\AppName\ga-visitor.sol` and then uses a thread to save to that file, see https://github.com/fbricker/haxe-ga/blob/066dc8791af0a4758e058208a5a0563ca66fb22d/src/googleAnalytics/Stats.hx.

After we init the analytics library we try to read save games from that same folder using `readDirectory`. This seems to fail every time on certain machines. We have currently worked around this issue by placing these two calls pretty far from each other.

Using Haxe 3.1.3 and hxcpp 3.1.39 or 3.1.68. hxcpp version doesn't seem to make a difference.

```
package;

class App {
	static function main():Void {
		googleAnalytics.Stats.init('UA-123456-1', 'bar.example.com');
		sys.FileSystem.readDirectory(openfl.utils.SystemPath.applicationStorageDirectory);
	}
}
```

**Comment by hughsando** [comment]
It would be great to see what is going on inside std.dll via the callstack.
You can turn this on by rebuilding the libs from the hxcpp project directory with:
neko build.n -debug
And then rebuilding the exe should bring in the debug dll, and show the stack.

**Comment by hughsando** [comment]
I believe this is now fixed.
