### ISSUE TITLE
SQLite SELECT Query Error if record not found.

### ISSUE THREAD

**Issue by Dimensionscape** [HaxeFoundation/hxcpp#895]
"Invalid sqlite result" error when I check to see if the result length is >0. Works right on other platforms. Should I be handling this differently or is this a bug?

**Comment by sonygod** [comment]
@jonasmalacofilho  will you take a look?

**Comment by jonasmalacofilho** [comment]
Can't reproduce it locally.

```
$ cat Test.hx 
class Test {
	static function main() {
		var cnx = sys.db.Sqlite.open(":memory:");
		var res = cnx.request("SELECT 1 foo, 'b' bar");
		if (res.length > 0)
			trace(res.next());
		cnx.close();
	}
}

$ haxe --cpp bin --main Test
[...]

$ bin/Test 
Test.hx:6: { foo => 1, bar => b }
```

Will need a minimal reproduceable example as well as Haxe and Hxcpp versions.  Probably best to mention the OS in use as well.

**Comment by Dimensionscape** [comment]
Sure, I will post the code when I am able to get back into the office. To clarify, as pointed out in the subject, the error is incurred when the record is **not** found.
 if (res.length > 0) else trace("record not found");

It works on Neko, but for cpp we had to work around it with try/catch. hxcpp 4.0.64, haxe 4, windows 10

**Comment by jonasmalacofilho** [comment]
@Dimensionscape 

Ok, by changing to your hxcpp version I can also reproduce the problem.  It's something that has already been fixed, but the patch hasn't reached a stable hxcpp release yet: #856 ("Handle .length and .nfields on empty result sets").

The fix is already available on the master branch, so if you manually install (and build) hxcpp from git you should be set.

---

@sonygod 

Please point me in the correct direction when you ping me for something that you know has been solved.  Even if I'm the author of a commit that fixes something doesn't mean that I'll immediately remember about it, and I can easily spend a bunch time rediscovering the same fix again.

**Comment by Dimensionscape** [comment]
Sorry, I didn't mean to waste your time, thanks so much for the quick reply.

**Comment by jonasmalacofilho** [comment]
Don't worry about it.

And @sonygod, perhaps I ended up being more harsh than I intended.  Please don't worry too much about it either.

**Comment by sonygod** [comment]
@jonasmalacofilho ,sorry for delay .

I post my code here

https://github.com/HaxeFoundation/hxcpp/issues/900
