### ISSUE TITLE
HXCPP GC - FIXES - IMPROVEMENTS - LINK TO DOWNLOAD

### ISSUE THREAD

**Issue by sibest** [HaxeFoundation/hxcpp#917]
WIP

**Comment by sibest** [comment]
Uploaded the source code

**Comment by Aurel300** [comment]
That's all nice but you this is an issue, not a PR? Where is the code?

> The first thing that I noticed is that it was using incredible big memory line size (128 bytes per line), ...

Why is that an issue? Multiple objects can go into one Immix line. By decreasing the line below 64 bytes, it is no longer aligned with CPU cache lines. Have you profiled your changes against the GC benchmarks?

**Comment by m0rkeulv** [comment]
not sure where to find your code (cant find a link or pull request), but i hope it includes the fix for HXCPP_GC_GENERATIONAL on android builds that you suggested :) https://github.com/HaxeFoundation/hxcpp/issues/906

**Comment by sibest** [comment]
Sorry, here is the source
[source.zip](https://github.com/HaxeFoundation/hxcpp/files/4743303/source.zip)
I've updated the code to use 64byte rows as suggested by @Aurel300 , as it improves the performance significantly

**Comment by hughsando** [comment]
So there are some things to think about.

Smaller row length will slow things down in general, but will also reduce fragmentation.  So it is about how these things interact that really needs to be measured in a variety of applications.

Large memory allocations can be surprisingly expensive in some cases.  It would be nice to have some typical application benchmarks to guide optimization there.

The mark thread count is really to reduce stop-the-world pause time - there are some defines to profile various aspects of  the collection and this is probably an important measure for games.

The mZeroed flag is tricky because blocks may either be zeroed by a background thread or at allocation time or at use time depending on some async details. So you should be quite sure this is handled correctly.

The solution for holes > MAX_HOLES is to ignore the remaining holes this collection and pick them up the next time around.

I think the inline allocator is only called for haxe objects, which are known to me smaller than the large_obj_size

**Comment by sibest** [comment]
I've updated the code on top. In my code base the inline allocator was asking for more than the large_obj_size. Tomorrow I will keep working on it.

**Comment by Aurel300** [comment]
Could you please make your code into a PR so it is easily viewable (and diffable) here on GitHub? The clickbait title is also not very helpful …

**Comment by sibest** [comment]
You are right, plus i've not finished yet so i've removed the whole post meantime.
